server:
  port: 8200

spring:
  datasource:
    url: jdbc:h2:mem:commerce
    driverClassName: org.h2.Driver
    password: password
    username: sa    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:      ddl-auto: create
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: commerceMS
  profiles:
    active: email
#  cloud:
#    config:
#      name: shop
#  config:
#    import: configserver:http://localhost:8888

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED
    
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
  metrics:
    enabled: true

management:
  endpoint:
    hystrix:
      stream:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
