server:
  port: 8200

spring:
  datasource:
    url: jdbc:h2:mem:commerce
    driverClassName: org.h2.Driver
    password: password
    username: sa
  application:
    name: commerceMS
  profiles:
    active: email
  cloud:
    config:
      name: shop
  config:
    import: configserver:http://localhost:8888
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
  metrics:
    enabled: true

management:
  endpoint:
    hystrix:
      stream:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

email:
  host: ${RSS_EMAIL_HOST:localhost}
  port: ${RSS_EMAIL_PORT:25}
  username: ${RSS_EMAIL_USERNAME:user}
  Password: ${RSS_EMAIL_PASSWORD:password}