apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app
spec:
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
      - name: config
        image: aypas/config
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888

