apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-app
spec:
  selector:
    matchLabels:
      app: eureka-app
  template:
    metadata:
      labels:
        app: eureka-app
    spec:
      containers:
      - name: myapp
        image: aypas/eureka-server
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
