server:
  port: 8100

spring:
  datasource:
    url: jdbc:h2:mem:inventory
  application:
    name: inventoryMS
  profiles:
    active: email
  cloud:
    config:
      name: shop
  config:
    import: configserver:http://localhost:8888