server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:mem:accounts
    driverClassName: org.h2.Driver
    password: password
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: accountsMS
  profiles:
    active: email
#  cloud:
#    config:
#      name: shop
#  config:
#    import: configserver:http://localhost:8888

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
  metrics:
    enabled: true
    
resilience4j:
  circuitbreaker:
    instances:
      accountService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:    
      exposure:
        include: health
  endpoint:
    health:  
      show-details: always
    hystrix:
      stream:
        enabled: true
    shutdown:
      enabled: true

        


#management:        
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:    
#      exposure:
#        include: health
#  endpoint:
#    health:  
#      show-details: always      

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
