{{- with .Values.frontend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deploymentName }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      containers:
      - name: {{ .deploymentName }}
        image: {{ .image }}:{{ .tag }}
        resources:
          limits:
            memory: {{quote .memoryLimit }}
            cpu: {{ quote .cpuLimit }}
        ports:
        - containerPort: {{ .containerPort }}
{{ end }}
