{{ if not .Values.ingress.useIngress }}
{{- with .Values.gateway}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
spec:
  selector:
    app: {{ .app }}
  ports:
  - port: {{ .containerPort }}
    targetPort: {{ .containerPort }}
  type: LoadBalancer
{{ end }}
{{ end }}