{{- with .Values.inventory }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
spec:
  selector:
    app: {{ .app }}
  ports:
  - port: {{ .containerPort }}
    targetPort: {{ .containerPort }}
{{ end }}
