parameters:
  - name: 'targetPath'
    type: string
  - name: 'artifact'
    type: string
  - name: 'tag'
    type: string
  - name: 'Dockerfile'
    type: string
  - name: 'repository'
    type: string

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: ${{ parameters.artifact }}
        itemPattern: '**.jar'
        targetPath: ${{ parameters.targetPath }}

    - task: Docker@2
      inputs:
        containerRegistry: ${{ parameters.repository }}
        repository: ${{ parameters.repository }}
        command: 'buildAndPush'
        Dockerfile: ${{ parameters.Dockerfile }}
        tags: ${{ parameters.tag }}