parameters:
  - name: 'targetPath'
    type: string
  - name: 'artifact'
    type: string
  - name: 'tag'
    type: string
  - name: 'Dockerfile'
    type: string
  - name: 'repository'
    type: string

steps:

  - task: Docker@2
    displayName: Create/Push Docker Image
    inputs:
      containerRegistry: ${{ parameters.repository }}
      repository: ${{ parameters.repository }}
      command: 'buildAndPush'
      Dockerfile: ${{ parameters.Dockerfile }}
      tags: ${{ parameters.tag }}