
parameters:
  - name: 'containerName'
    type: string
  - name: 'imageName'
    type: string
  - name: 'tag'
    type: string
  - name: 'activeSvc'
    type: string
  - name: 'aksConnection'
    type: string
  - name: 'releaseName'
    type: string
  - name: 'nameSpace'
    type: string

  jobs:
  - job: ApplyAndDeploy
    displayName: Helm Deployment
    steps:
    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: './helm/testchart/'
        destination: './helm/'
    
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: ${{ parameters.aksConnection }}
        command: 'upgrade'
        arguments: '--install --atomic --reuse-values --dry-run'
        releaseName: ${{ parameters.releaseName }}
        namespace: ${{ parameters.nameSpace }}
        chartType: 'FilePath'
        chartPath: './helm/'
        overrideValues: |
          ${{ parameters.activeSvc }}.deploy.image.name=${{ parameters.containerName}}/${{ parameters.imageName }}
          ${{ parameters.activeSvc }}.deploy.image.tag=${{ parameters.tag }}
        valueFile: './helm/values.yaml'
