
parameters:
  - name: 'triggerBranch'
    type: string
    default: 'devops_pipeline'


trigger:
  branches:
    include:
    - ${{ parameters.triggerBranch }}

    
variables:
- name: service
    ${{ if eq(variables['Build.SourcesDirectory'], './base') }}: 
      value: base
    ${{ if eq(variables['Build.SourcesDirectory'], './config') }}: 
      value: RevShopConfig
    ${{ if eq(variables['Build.SourcesDirectory'], './inventory') }}: 
      value: inventory
    ${{ if eq(variables['Build.SourcesDirectory'], './eureka-server') }}: 
      value: eureka-server
    ${{ if eq(variables['Build.SourcesDirectory'], './commerce') }}: 
      value: RevShopCommerce
    ${{ if eq(variables['Build.SourcesDirectory'], './accounts') }}: 
      value: RevShopAccounts
    ${{ if eq(variables['Build.SourcesDirectory'], './Spring-Cloud-Gateway') }}: 
      value: spring-cloud-gateway