
parameters:
  - name: 'triggerBranch'
    type: string
    default: 'devops_pipeline'


trigger:
  branches:
    include:
    - ${{ parameters.triggerBranch }}

    
variables:
- name: service
  value:
  ${{ if eq(variables['Build.SourcesDirectory'], './base') }}: base
  ${{ if eq(variables['Build.SourcesDirectory'], './config') }}: RevShopConfig
  ${{ if eq(variables['Build.SourcesDirectory'], './inventory') }}: inventory
  ${{ if eq(variables['Build.SourcesDirectory'], './eureka-server') }}: eureka-server
  ${{ if eq(variables['Build.SourcesDirectory'], './commerce') }}: RevShopCommerce
  ${{ if eq(variables['Build.SourcesDirectory'], './accounts') }}: RevShopAccounts
  ${{ if eq(variables['Build.SourcesDirectory'], './Spring-Cloud-Gateway') }}: spring-cloud-gateway