# The idea is to be inclusive of all source directories. (I.E. Commerce, Accounts, Eureka, Gateway, Inventory, Config, and Base(?))
# And using the  variable to set a condition that will set variables.

trigger:
  branches:
    include: 
    - devops_pipeline

# Set some variables with base value to be change by script.
variables:
  accounts-service: false
  base: false
  commerce-service: false
  config-service: false
  eureka-service: false
  inventory-service: false
  gateway-service: false

parameters:
- name: serviceConditions
  type: object
  default:
  - base:
    name: 'base'
    value: false
  - accounts-service:
    name: 'accounts-service'
    value: false
  - commerce-service:
    name: 'commerce-service'
    value: false
  - config-service:
    name: 'config-service'
    value: false
  - eureka-service:
    name: 'eureka-service'
    value: false
  - inventory-service:
    name: 'inventory-service'
    value: false
  - gateway-service:
    name: 'gateway-service'
    value: false

stages:
- stage: PipelineLogic
  displayName: Testing... testing...
  jobs:
  - job: Test
    steps:
   
      # This script will check the Repo for changes and store them in a variable updatedFiles.
      # The script will iterate over every object stored in updatedFiles to select paths with changes.
      # Pipeline variable will be updated from 'false' to 'True' if a change was made in that path.
      # This step controls which build tasks will be triggered.

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $updatedFiles = git diff HEAD HEAD~ --name-only
          $updatedFiles | ForEach-Object {
              Switch -Wildcard ($_ ) {
                  'accounts/*' { Write-Output "##vso[task.setvariable variable=accounts]True" }
                  'base/*' { Write-Output "##vso[task.setvariable variable=base]True" }
                  'commerce/*' { Write-Output "##vso[task.setvariable variable=commerce-service]True" }
                  'config/*' { Write-Output "##vso[task.setvariable variable=config-service]True" }
                  'eureka-server/*' { Write-Output "##vso[task.setvariable variable=eureka-service]True" }
                  'inventory/*' { Write-Output "##vso[task.setvariable variable=inventory-service]True" }
                  'Spring-Cloud-Gateway/*' { Write-Output "##vso[task.setvariable variable=gateway-service]True" }
              }
          }
          
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |   
          
          if ( $$(base) )
          {
              Write-Output "##vso[task.setvariable variable=accounts-service]True"
              Write-Output "##vso[task.setvariable variable=commerce-service]True"
              Write-Output "##vso[task.setvariable variable=inventory-service]True"
          }

      # Output Variables: If true, these are the services that will be built later in the pipeline.

    - ${{ each service in parameters.serviceConditions }}:
      - script: echo '${{ service.name }} has been updated - $(${{ service.name }})'
        displayName:  Running ${{ service.name }} - $(${{ service.name }}
    

