# The idea is to be inclusive of all source directories. (I.E. Commerce, Accounts, Eureka, Gateway, Inventory, Config, and Base(?))
# And using the Build.SourcesDirectory variable to set a condition that will set variables.
trigger:
  branches:
    include: 
    - devops_pipeline

# Set some variables with base value to be change by script.
variables:
  accounts-service: false
  base: false
  commerce-service: false
  config-service: false
  eureka-service: false
  inventory-service: false
  gateway-service: false



stages:
- stage: PipelineLogic
  displayName: Testing... testing...
  jobs:
  - job: Test
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $editedFiles = git diff HEAD HEAD~ --name-only
          $editedFiles | ForEach-Object {
              Switch -Wildcard ($_ ) {
                  'accounts/*' { Write-Output "##vso[task.setvariable variable=accounts-service]True" }
                  'base/*' { Write-Output "##vso[task.setvariable variable=base]True" }
                  'commerce/*' { Write-Output "##vso[task.setvariable variable=commerce-service]True" }
                  'config/*' { Write-Output "##vso[task.setvariable variable=config-service]True" }
                  'eureka-server/*' { Write-Output "##vso[task.setvariable variable=eureka-service]True" }
                  'inventory/*' { Write-Output "##vso[task.setvariable variable=inventory-service]True" }
                  'Spring-Cloud-Gateway/*' { Write-Output "##vso[task.setvariable variable=gateway-service]True" }
              }
          }
    - script: |
        echo $(accounts-service)
        echo $(base)
        echo $(config-service)
        echo $(eureka-service)
        echo $(inventory-service)
        echo $(gateway-service)
  
# - template: ./build-test-stage-template.yml
#   parameters:
#     mavenPomFile: "./$(service)/pom.xml"
#     options: "-f $(service)/pom.xml"
#     targetPath: "./$(service)/target/$(service)-0.0.1-SNAPSHOT.jar"
#     artifact: $(service)
#     displayName: '${{ variables.service }} Build and Test'

# - template: ./docker-stage-template.yml
#   parameters:
#     stage: CommitImage
#     displayName: '${{ variables.service }} Image Build and Push to ACR/Dockerhub'
#     targetPath: './dockerize'
#     Dockerfile: 'dockerize/gateway.Dockerfile'
#     artifact: $(service)
#     tags: "$(Build.SourceVersion)"
#     repository: "team4revops/$(service)"

# - template: ./docker-stage-template.yml
#   parameters:
#     stage: LatestImage
#     displayName: '${{ variables.service }} Image Build and Push to ACR/Dockerhub'
#     targetPath: './dockerize'
#     Dockerfile: 'dockerize/gateway.Dockerfile'
#     artifact: $(service)
#     tags: latest
#     repository: "team4revops/$(service)"

# - template: ./helm-deploy-template.yml
#   parameters:
#     containerName: team4revops
#     imageName: $(service)
#     tag: latest
#     helmCommand: Upgrade
#     disableSvc1: quiz
#     disableSvc2: flashcard
#     activeSvc: gateway