# The idea is to be inclusive of all source directories. (I.E. Commerce, Accounts, Eureka, Gateway, Inventory, Config, and Base(?))
# And using the  variable to set a condition that will set variables.

trigger:
  branches:
    include: 
    - devops_pipeline

# Set some variables with base value to be change by script.
variables:
  accounts-service: false
  base: false
  commerce-service: false
  config-service: false
  eureka-service: false
  inventory-service: false
  gateway-service: false

parameters:
- name: serviceConditions
  type: object
  default:
  - base: false
  - accounts-service: false
  - commerce-service: false
  - config-service: false
  - eureka-service: false
  - inventory-service: false
  - gateway-service: false

stages:
- stage: PipelineLogic
  displayName: Testing... testing...
  jobs:
  - job: Test
    steps:
    - ${{ each service in parameters.serviceConditions }}:
      - script: echo '${{ Object.keys(service)[0] }}'
      
      # This script will check the Repo for changes and store them in a variable updatedFiles.
      # The script will iterate over every object stored in updatedFiles to select paths with changes.
      # Pipeline variable will be updated from 'false' to 'True' if a change was made in that path.
      # This step controls which build tasks will be triggered.

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $updatedFiles = git diff HEAD HEAD~ --name-only
          $updatedFiles | ForEach-Object {
              Switch -Wildcard ($_ ) {
                  'accounts/*' { Write-Output "##vso[task.setvariable variable=accounts-service]True" }
                  'base/*' { Write-Output "##vso[task.setvariable variable=base]True" }
                  'commerce/*' { Write-Output "##vso[task.setvariable variable=commerce-service]True" }
                  'config/*' { Write-Output "##vso[task.setvariable variable=config-service]True" }
                  'eureka-server/*' { Write-Output "##vso[task.setvariable variable=eureka-service]True" }
                  'inventory/*' { Write-Output "##vso[task.setvariable variable=inventory-service]True" }
                  'Spring-Cloud-Gateway/*' { Write-Output "##vso[task.setvariable variable=gateway-service]True" }
              }
          }
          
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |   
          Write-Output $(base)
          if ( $$(base) )
          {
              Write-Output "##vso[task.setvariable variable=accounts-service]True"
              Write-Output "##vso[task.setvariable variable=commerce-service]True"
              Write-Output "##vso[task.setvariable variable=inventory-service]True"
          }

      # Output Variables: If true, these are the services that will be built later in the pipeline.

    - script: |
        echo $(accounts-service)
        echo $(base)
        echo $(config-service)
        echo $(eureka-service)
        echo $(inventory-service)
        echo $(gateway-service)
    

