# The idea is to be inclusive of all source directories. (I.E. Commerce, Accounts, Eureka, Gateway, Inventory, Config, and Base(?))
# And using the variable to set a condition that will set pipeline variables variables that will control the flow of the pipeline.

trigger:
  branches:
    include: 
    - devops_pipeline
    - experimental-pipeline

# Was this directory updated? These variables will hold the answer 
variables:
  accounts: false
  base: false
  commerce: false
  config: false
  eureka-server: false
  inventory: false
  Spring-Cloud-Gateway: false

parameters:
- name: serviceConditions
  type: object
  default:
  - base:
    name: 'base'
    jobName: 'BaseBuild'
  - accounts:
    name: 'accounts'
    requiresBase: true
    jobName: 'AccountsBuild'
  - commerce:
    name: 'commerce'
    requiresBase: true
    jobName: 'CommerceBuild'
  - config:
    name: 'config'
    jobName: 'ConfigBuild'
  - eureka-server:
    name: 'eureka-server'
    jobName: 'EurekaBuild'
  - inventory:
    name: 'inventory'
    requiresBase: true
    jobName: 'InventoryBuild'
  - Spring-Cloud-Gateway:
    name: 'Spring-Cloud-Gateway'
    jobName: 'SpringBuild'

stages:
- stage: Check
  displayName: Check Service Changes, Test and Build
  jobs:
  - job: CheckChanges
    steps:
   
      # This script will check the Repo for changes and store them in a variable updatedFiles.
      # The script will iterate over every object stored in updatedFiles to select paths with changes.
      # Pipeline variable will be updated from 'false' to 'True' if a change was made in that path.
      # This step controls which build tasks will be triggered.

    # - task: PowerShell@2
    #   name: checkBuild
    #   displayName: Checking Service Directories
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       $updatedFiles = git diff HEAD HEAD~ --name-only
    #       $updatedFiles | ForEach-Object {
    #           Switch -Wildcard ($_ ) {
    #               'accounts/*' { Write-Output "##vso[task.setvariable variable=accounts;isOutput=true]True" }
    #               'base/*' { Write-Output "##vso[task.setvariable variable=base;isOutput=true]True" }
    #               'commerce/*' { Write-Output "##vso[task.setvariable variable=commerce;isOutput=true]True" }
    #               'config/*' { Write-Output "##vso[task.setvariable variable=config;isOutput=true]True" }
    #               'eureka-server/*' { Write-Output "##vso[task.setvariable variable=eureka-server;isOutput=true]True" }
    #               'inventory/*' { Write-Output "##vso[task.setvariable variable=inventory;isOutput=true]True" }
    #               'Spring-Cloud-Gateway/*' { Write-Output "##vso[task.setvariable variable=Spring-Cloud-Gateway;isOutput=true]True" }
    #           }
    #       }
        
    - powershell: |
        $updatedFiles = git diff HEAD HEAD~ --name-only
          $updatedFiles | ForEach-Object {
              Switch -Wildcard ($_ ) {
                  'accounts/*' { Write-Output "##vso[task.setvariable variable=accounts;isOutput=true]True" }
                  'base/*' { Write-Output "##vso[task.setvariable variable=base;isOutput=true]True" }
                  'commerce/*' { Write-Output "##vso[task.setvariable variable=commerce;isOutput=true]True" }
                  'config/*' { Write-Output "##vso[task.setvariable variable=config;isOutput=true]True" }
                  'eureka-server/*' { Write-Output "##vso[task.setvariable variable=eureka-server;isOutput=true]True" }
                  'inventory/*' { Write-Output "##vso[task.setvariable variable=inventory;isOutput=true]True" }
                  'Spring-Cloud-Gateway/*' { Write-Output "##vso[task.setvariable variable=Spring-Cloud-Gateway;isOutput=true]True" }
              }
          }
      name: checkBuild

    - task: PowerShell@2
      name: secondCheckBuild
      displayName: Rebuild services, if base.
      inputs:
        targetType: 'inline'
        script: |   
          
          if ( $$(checkBuild.base) )
          {
              Write-Output "##vso[task.setvariable variable=accounts;isOutput=true]True"
              Write-Output "##vso[task.setvariable variable=commerce;isOutput=true]True"
              Write-Output "##vso[task.setvariable variable=inventory;isOutput=true]True"
          }
    - script: |
          echo 'Base will rebuild: $(checkBuild.base)'
          echo 'Accounts will rebuild: $(secondCheckBuild.accounts)'
          echo 'Commerce will rebuild: $(secondCheckBuild.commerce)'
          echo 'Inventory will rebuild: $(secondCheckBuil.inventory)'
          echo 'Config will rebuild: $(checkBuild.config)'
          echo 'Eureka Server will rebuild: $(checkBuild.eureka-server)'
          echo 'Spring Cloud Gateway will rebuild: $(checkBuild.Spring-Cloud-Gateway)'

  - ${{ each service in parameters.serviceConditions }}:
    - job: ${{ service.jobName }}
      pool:
        name: java-16
      dependsOn: CheckChanges
      variables:
        currentBuild: $[ dependencies.CheckChanges.outputs['checkBuild.${{ service.name }}'] ] 
      condition: or(eq(variables['checkBuild.${{ service.name }}'], 'True'), eq(variables['secondCheckBuild.$service.name']))
      steps:
      - script: echo '${{ service.name }} has been updated - $(${{ service.name }})'
        displayName:  'Checking ${{ service.name }}'
      
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: $(organization)
          scannerMode: 'CLI'
          configMode: 'file'

      - script:  echo 'test'
